.TH n 1 
.SH NAME
n - notes 
.SH SYNOPSIS
.B n 
.BI [
.B p
.B r
.B d
.B e
.BI ]
.SH DESCRIPTION
.B n
A very small note taking app designed to make life a tiny bit nicer
.SH OPTIONS
.TP
.BI p 
Print all note names
.TP
.BI d 
Delete a note from a list of names
.TP
.BI r 
Reads a note from a list of name
.TP
.BI e
Edits a note from a list
.SH DIRECTORIES
.TP
.B ~/.cache/notes
The default place notes are kepts
.SH SEE ALSO
.BR sh (1),
